---
- name: get nodes user-data
  hosts: ram-nodes
  tags: user-data
  roles:
    - userdata

- name: config hostname and network
  hosts: nodes
  tags: host-config
  roles:
    - hostconfig

- name: deploy config
  hosts: deploy
  tags: deploy-config
  roles:
    - deployconfig
