---

- name: set hostname
  shell: "hostnamectl set-hostname {{ HOSTNAME }}"

- name: config network
  template:
    src: templates/network.yml
    dest: /etc/netplan/00-installer-config.yaml

- name: delete dhcp route
  shell: "ip route del default via 192.168.100.20"
  ignore_errors: yes

- name: netplan apply
  shell: "netplan apply"

- name: copy file
  copy: src={{ item }}  dest=/tmp/
  loop:
    - "../pkg/libtinfo5_6.2-0ubuntu2_amd64.deb"
    - "../pkg/libncurses5_6.2-0ubuntu2_amd64.deb"
    - "../pkg/megacli_8.07.14-1_all.deb"

- name: install pkgs
  command: "dpkg -i /tmp/{{ item }}"
  loop:
    - "libtinfo5_6.2-0ubuntu2_amd64.deb"
    - "libncurses5_6.2-0ubuntu2_amd64.deb"
    - "megacli_8.07.14-1_all.deb"

- name: ping
  shell: "ping www.baidu.com -c 3"
  ignore_errors: yes
